[project]
name = {{cookiecutter.project_name}}
channels = [
    'https://repo.prefix.dev/ecoscope-workflows/',
    'https://repo.prefix.dev/ecoscope-workflows-custom/',
    "file:///tmp/ecoscope-workflows/release/artifacts/",
    "file:///tmp/ecoscope-workflows-custom/release/artifacts/",
    'conda-forge',
]
platforms = ['linux-64', 'osx-arm64']

[dependencies]
curl = "*"
rattler-build = "*"
yq = "*"
hatch = "*"

[dependencies.ecoscope-workflows-core]
channel = 'https://repo.prefix.dev/ecoscope-workflows/'
version = '0.2.4.*'

[feature.compile.dependencies]

[feature.compile.dependencies.ecoscope-workflows-core]
version = "*"
channel = "https://repo.prefix.dev/ecoscope-workflows/"

[feature.compile.dependencies.ecoscope-workflows-ext-{{cookiecutter.project_name}}]
version = "*"
channel = "file:///tmp/ecoscope-workflows-custom/release/artifacts/"

[environments]
compile = { features = [
    "compile",
], solve-group = "compile", no-default-feature = true }

[tasks]
[tasks.build-release]
cmd = './publish/build.sh'

[tasks.pytest-310]
cmd = './dev/pytest-task.sh 310'

[tasks.pytest-311]
cmd = './dev/pytest-task.sh 311'

[tasks.pytest-312]
cmd = './dev/pytest-task.sh 312'

[tasks.compile-{{cookiecutter.workflow_name}}]
cmd = './dev/recompile.sh {{cookiecutter.workflow_name}} --install'
depends-on = ["build-release"]

[tasks.recompile-{{cookiecutter.workflow_name}}]
cmd = './dev/recompile.sh {{cookiecutter.workflow_name}} --update'
depends-on = ["build-release"]
