[project]
name = "{{cookiecutter.repo_name}}"
channels = [
    "file:///tmp/ecoscope-workflows/release/artifacts/",
    "file:///tmp/ecoscope-workflows-custom/release/artifacts/",
    'https://repo.prefix.dev/ecoscope-workflows/',
    'https://repo.prefix.dev/ecoscope-workflows-custom/',
    'conda-forge',
]
platforms = ['linux-64', 'osx-arm64']

[dependencies]
curl = "*"
rattler-build = "*"
yq = "*"
hatch = "*"

[feature.compile.dependencies]
ecoscope-workflows-ext-{{cookiecutter.project_name}} = "*"

ecoscope-workflows-core = "0.2.9.*"
# Here we don't specify the channel on purpose, as we want to use the local channel if it exists,
# otherwise we fall back to the remote channel.
# If you want to ensure a specific channel to incorporate your local changes, you can uncomment the line below.
# ecoscope-workflows-ext-{{cookiecutter.project_name}} = { version = "*", channel = "file:///tmp/ecoscope-workflows-custom/release/artifacts/" }

[environments]
compile = { features = [
    "compile",
], solve-group = "compile", no-default-feature = true }

[tasks]
[tasks.build-release]
cmd = './publish/build.sh'

[tasks.pytest-310]
cmd = './dev/pytest-task.sh 310'

[tasks.pytest-311]
cmd = './dev/pytest-task.sh 311'

[tasks.pytest-312]
cmd = './dev/pytest-task.sh 312'

[feature.compile.tasks.compile-{{cookiecutter.workflow_name}}]
cmd = './dev/recompile.sh {{cookiecutter.workflow_name}} --install'
depends-on = ["build-release"]

[feature.compile.tasks.recompile-{{cookiecutter.workflow_name}}]
cmd = './dev/recompile.sh {{cookiecutter.workflow_name}} --update'
depends-on = ["build-release"]
